<?php
require_once 'includes/content.php';
$copy=xuverse_content('copy'); xuverse_public_start('XuVerse', $copy['hero_intro']);
?>
<section class="public-hero container"><div><p class="eyebrow"><?= e($copy['hero_kicker']) ?></p><p class="identity">B K Suraj · <?= e($copy['location']) ?></p><h1><?= e($copy['hero_headline']) ?></h1><p class="lead"><?= e($copy['hero_intro']) ?></p><div class="public-actions"><a class="btn" href="<?= e(xuverse_url('projects')) ?>">See My Work</a><a class="btn secondary-btn" href="<?= e(xuverse_url('resume')) ?>">Resume</a><a class="text-link" href="<?= e(xuverse_url('contact')) ?>">Let’s Connect →</a></div><p class="focus-line"><?= e($copy['current_focus']) ?></p></div><img class="public-portrait" src="<?= e(xuverse_url('assets/images/public/portrait.webp')) ?>" alt="Portrait of B K Suraj" width="360" height="480" fetchpriority="high"></section>
<section class="section container"><p class="eyebrow">Selected work</p><h2>Ideas taking shape.</h2><div class="public-grid"><?php xuverse_public_card(xuverse_content('articles')[3],'articles'); xuverse_public_card(xuverse_content('projects')[0],'projects',xuverse_content('projects')[0]['image']); ?><article class="public-card"><p class="eyebrow">Media</p><h2><a href="<?= e(xuverse_url('videos/global-college-2026')) ?>">Dong-Eui Global College 2026</a></h2><p>Selected university promotional media work.</p><a class="text-link" href="<?= e(xuverse_url('videos/global-college-2026')) ?>">Watch video →</a></article></div></section>
<section class="section container"><div class="public-grid four-areas"><?php foreach(['Build'=>['projects',$copy['projects_intro']],'Create'=>['media',$copy['media_intro']],'Write'=>['articles',$copy['articles_intro']],'Explore'=>['articles/same-moment-different-meaning',$copy['research_intro']]] as $label=>$area): ?><div><h2><a href="<?= e(xuverse_url($area[0])) ?>"><?= e($label) ?></a></h2><p><?= e($area[1]) ?></p></div><?php endforeach; ?></div></section>
<section class="section container"><p class="eyebrow">Writing</p><h2>Looking a little closer.</h2><div class="public-grid"><?php foreach(array_slice(xuverse_content('articles'),0,3) as $a) xuverse_public_card($a,'articles'); ?></div></section>
<section class="section container"><p class="eyebrow">Selected media</p><h2>Images, movement, and community.</h2><p><?= e($copy['media_intro']) ?></p><a class="text-link" href="<?= e(xuverse_url('media')) ?>">Explore media →</a></section>
<section class="section container connection"><h2><?= e($copy['contact_heading']) ?></h2><p><?= e($copy['contact_intro']) ?></p><a class="btn" href="<?= e(xuverse_url('contact')) ?>">Connect</a></section>
<?php include 'includes/footer.php'; ?>
